### ISSUE TITLE
CSS refactoring

### ISSUE THREAD

**Issue by 55** [meteorcrowd/crowducate-next#59]
## Tasks
- [ ] Define/choose style guide
- [ ] Organize existing less files into folder hierarchy
- [ ] Refine duplicate less code in to common less file(s)
## Examples

Here are some great examples we can use:
- Github - http://markdotto.com/2014/07/23/githubs-css/
- Codepen - http://codepen.io/chriscoyier/blog/codepens-css
- Medium - https://medium.com/@fat/mediums-css-is-actually-pretty-fucking-good-b8e2a6c78b06

**Comment by brylie** [comment]
What will the deliverable be for this task? How will we know when it is complete? E.g. will we have a 'design guidelines' document, a refactor of our own CSS, statistics about lines of code in our CSS?

**Comment by brylie** [comment]
Basically, knowing more about this task will help us to plan and fit it into a sprint.

**Comment by 55** [comment]
First, what comes to my mind is to organize LESS files, e.g., each template has its own LESS file.
