### ISSUE TITLE
Switch rich text editor

### ISSUE THREAD

**Issue by 55** [meteorcrowd/crowducate-next#74]
Noticed a bug, when editing course, if I click on "Done editing" Summernote doesn't exit. Maybe that's a problem with summernote, but not sure.

![screenshot-localhost 3000 2015-03-11 20-00-47](https://cloud.githubusercontent.com/assets/7489044/6603376/5f1e6440-c82a-11e4-8b65-ab933e3a9c1f.png)

**Comment by brylie** [comment]
It looks like there are two sides of this bug:
- When the user clicks the lesson text, the Summernote is always rendered, whether or not edit mode is active
- When the user exits Edit mode, the Summernote editor destroy() method is not called

An alternative approach to event handling is to use the Template.autorun to dynamically toggle the inline editor depending on a reactive data source. There is an example of this code in the [lesson title autorun](https://github.com/Crowducate/crowducate-next/blob/master/client/templates/course/lesson/title/title.js#L34-L59).

## Todo
- [ ] Review the [Template.lesson.events 'click .lesson-text'](https://github.com/Crowducate/crowducate-next/blob/master/client/templates/course/lesson/lesson.js#L18-L21) code
- [ ] Review the [lesson title template autorun](https://github.com/Crowducate/crowducate-next/blob/master/client/templates/course/lesson/title/title.js#L34-L59) code for an example of how to create/destroy inline editable elements
- [ ] Refactor the create() and destroy() process to use Template.autorun, eliminating the event handling code

**Comment by brylie** [comment]
What started as a relatively simple re-factor led to some difficulty related to Summernote. I am considering a different rich text editor, and have created a [hackpad document](https://crowducate.hackpad.com/Rich-Text-Editor-Comparison-TiUpGjjshc8).

**Comment by brylie** [comment]
I am considering using the [babrahams:editable-text-wysiwyg-bootstrap-3](https://github.com/jackadams/meteor-editable-text-wysiwyg-bootstrap-3/) rich text editor.
